services:
  postgres:
    image: postgres:15
    container_name: minibank-postgres
    environment:
      POSTGRES_DB: minibank
      POSTGRES_USER: minibank
      POSTGRES_PASSWORD: minibank_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minibank-network

  minibank-app:
    build: .
    container_name: minibank-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/minibank
      - SPRING_DATASOURCE_USERNAME=minibank
      - SPRING_DATASOURCE_PASSWORD=minibank_pass
    networks:
      - minibank-network

networks:
  minibank-network:
    driver: bridge

volumes:
  pgdata: